/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#f8f9ff',
        'surface-dim': '#d0dbed',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e6eeff',
        'surface-container-high': '#dee9fc',
        'surface-container-highest': '#d9e3f6',
        'on-surface': '#121c2a',
        'on-surface-variant': '#404940',
        'inverse-surface': '#27313f',
        'inverse-on-surface': '#eaf1ff',
        'outline': '#707a6f',
        'outline-variant': '#bfc9bd',
        'surface-tint': '#1f6c3a',
        'primary': '#004c22',
        'on-primary': '#ffffff',
        'primary-container': '#166534',
        'on-primary-container': '#93e0a2',
        'inverse-primary': '#8bd79b',
        'secondary': '#4648d4',
        'on-secondary': '#ffffff',
        'secondary-container': '#6063ee',
        'on-secondary-container': '#fffbff',
        'tertiary': '#5300b7',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#6d24de',
        'on-tertiary-container': '#dac6ff',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#a6f4b5',
        'primary-fixed-dim': '#8bd79b',
        'on-primary-fixed': '#00210b',
        'on-primary-fixed-variant': '#005226',
        'secondary-fixed': '#e1e0ff',
        'secondary-fixed-dim': '#c0c1ff',
        'on-secondary-fixed': '#07006c',
        'on-secondary-fixed-variant': '#2f2ebe',
        'tertiary-fixed': '#eaddff',
        'tertiary-fixed-dim': '#d2bbff',
        'on-tertiary-fixed': '#25005a',
        'on-tertiary-fixed-variant': '#5a00c6',
        'background': '#f8f9ff',
        'on-background': '#121c2a',
        'surface-variant': '#d9e3f6',
        'warning': '#d97706',
        'sidebar-bg': '#eff4ff',
        'table-header-bg': '#eff4ff',
        'surface-cream': '#f8f9ff',
        'active-highlight': '#f0b134',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
        gutter: '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'sidebar-width': '280px',
      },
      maxWidth: {
        'max-width': '1440px',
      },
      fontFamily: {
        sans: ['Geist', 'sans-serif'],
        mono: ['Geist Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'mono-md': ['13px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
